### ISSUE TITLE
Grafana crashed, unknown reason

### ISSUE THREAD

**Issue by danzipie** [energywebfoundation/ewc-system-tests#22]
I was adding new nodes with `addNode.sh`. Grafana crashed at 11:50. I noticed it after lunch, and I gave this command to restart:
`docker-compose restart`

See the figure below:

<img width="914" alt="Screen Shot 2019-04-24 at 13 23 56" src="https://user-images.githubusercontent.com/6286268/56655918-5e9c3800-6694-11e9-8a82-583cc6ffe680.png">

Is there a log file where I can find more information about the root cause of the crash?

**Comment by thereapman** [comment]
Would need logfiles etc. for this to resolve. see answer above

**Comment by danzipie** [comment]
It never happened with the last version of scripts. I close it.
